import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger,
} from "@/components/ui/menubar"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
         
      <Menubar>
  <MenubarMenu>
    <MenubarTrigger>home</MenubarTrigger>
    <MenubarContent>
      <MenubarItem>
        blogs <MenubarShortcut>⌘T</MenubarShortcut>
      </MenubarItem>
      <MenubarItem>projects</MenubarItem>
      <MenubarSeparator />
      <MenubarItem> contact </MenubarItem>
    
    </MenubarContent>
  </MenubarMenu>
</Menubar>
        
        {children}
     

      </body>
    </html>
  );
}
